---
- name: install boto3
  pip: name=boto3 state=present executable=pip3

- name: install awscli
  pip: name=awscli state=present

- name: Setup AWS cli
  lineinfile:
    dest=~/.bashrc
    line="[ -f /vagrant/code/aws-utils.sh ] && source /vagrant/code/aws-utils.sh"
    state=present
    insertafter=EOF
    create=True
  become_user: ubuntu

- name: Setup PYTHON PATH
  lineinfile:
    dest=~/.bashrc
    line="export PYTHONPATH=/vagrant/code:$PYTHONPATH"
    state=present
    insertafter=EOF
    create=True
  become_user: ubuntu

